### ISSUE TITLE
1-Definicion de Software.

### ISSUE THREAD

**Issue by brumar777** [Tatiana-Urbina/Grupo-3-Aula-2#1]

**Comment by acostanoeliacba** [comment]
El software son los programas, los documentos asociados y la configuración de datos que se necesitan para hacer que estos programas operen de manera correcta.
Es decir, comprende el conjunto de los componentes lógicos necesarios que hace posible la realización de tareas específicas, en contraposición a los componentes físicos que son llamados hardware.
