### ISSUE TITLE
18-Explicar la Retrospectiva del Sprint (Sprint Retrospective)

### ISSUE THREAD

**Issue by brumar777** [Tatiana-Urbina/Grupo-3-Aula-2#18]

**Comment by LForeste** [comment]
El _Sprint Restrospective_  "es planificar formas de aumentar la calidad y la efectividad (...)" (Schwaber & Sutherland, p. 10,  2020)
Aquí, el _Scrum Team_ inspecciona cómo se desarrolló el último _Sprint_ en relación a las personas, interacciones, procesos, herramientas y la definición de Terminado.  Concretamente, el _Scrum Team_ evalúa e identifica aciertos, qué problemas fueron surgiendo y cómo se resolvieron o no.
El _Sprint Restrospective_ constituye la conclusión del _Sprint_: debería tener un tiempo máximo de duración de hasta tres horas, para un  _Sprint_  de un mes.

**Comment by LForeste** [comment]
Es el evento que concluye el _Sprint._
