### ISSUE TITLE
19-¿Qué son los artefactos en SCRUM (Scrum Artifacts)?

### ISSUE THREAD

**Issue by brumar777** [Tatiana-Urbina/Grupo-3-Aula-2#19]

**Comment by LForeste** [comment]
"Los artefactos de Scrum representan trabajo o valor. Están diseñados para maximizar la transparencia de la información clave. Por lo tanto, todas las personas que los inspeccionan tienen la misma base de adaptación.
Cada artefacto contiene un compromiso para garantizar que proporcione información que mejore la transparencia y el enfoque frente al cual se pueda medir el progreso:
> ● Para el _Product Backlog_, es el Objetivo del Producto.
> ● Para el _Sprint Backlog,_ es el Objetivo del Sprint.
> ● Para el _Increment_ es la Definición de Terminado.
Estos compromisos existen para reforzar el empirismo y los valores de Scrum para el _Scrum Team_ y sus interesados.

**Comment by LForeste** [comment]
Definición de artefactos Scrum.
