### ISSUE TITLE
2-Caracteristicas del Software.

### ISSUE THREAD

**Issue by brumar777** [Tatiana-Urbina/Grupo-3-Aula-2#2]

**Comment by acostanoeliacba** [comment]
CARACTERÍSTICAS:
 
* Es intangible. 
* Tiene alto contenido Intelectual. 
* Su proceso de desarrollo es humano intensivo, basado en equipos y construidos en proyectos. 
* Puede ser potencialmente modificado, en forma permanente. (Robert Cochram). 
* El software no se manufactura, se desarrolla. 
* El software no se desgasta. 
* A pesar de la tendencia de la industria a desarrollar por componentes, gran parte del software aún se construye a medida. (Pressman).
